version: 2.1

jobs:
  test_tool_and_runtime_java:
    machine: true
    steps:
      - run: echo "Hello java"
  test_runtime:
    parameters:
      target:
        description: The target
        type: string
        default: java
    docker:
      - image: cimg/openjdk:8.0
    environment:
      TARGET: << parameters.target >>
    steps:
      - run:
          name: Install << parameters.target >> pre-requisites
          command: |
            f=".circleci/scripts/install-linux-$TARGET.sh"; ! [ -x "$f" ] || "$f"
      - checkout
      - run:
          name: Build ANTLR4 tool
          command: mvn -B -V -DskipTests=true -Dmaven.javadoc.skip=true install
      - run:
          name: Test << parameters.target >> runtime
          command: |
            .circleci/scripts/run-tests-$TARGET.sh
  test_runtime_group:
    machine: true
    parameters:
      test-group:
        description: The section
        type: string
        default: MAIN
      target:
        description: The target
        type: string
        default: java
    steps:
      - run: echo "Hello <<parameters.target>> <<parameters.test-group>>"

workflows:
  build:
    jobs:
      - test_tool_and_runtime_java
      - test_runtime: # invokes the parameterized job
          matrix:
            parameters:
#              target: [ dart, go, python2, python3, javascript ]
              target: [ go ]
      - test_runtime_group: # invokes the parameterized job
          matrix:
            parameters:
#              target: [ cpp, dotnet, swift ]
#              group: [ LEXER, PARSER, RECURSION ]
              test-group: [ LEXER ]
              target: [ cpp ]
