version: 2.1

jobs:
  test_java_tool_and_runtime:
    machine: true
    steps:
      - run: echo "Hello java"
  test_runtime_target:
    parameters:
      target:
        description: The target
        type: string
        default: java
    docker:
      - image: cimg/openjdk:8.0
    environment:
      TARGET: << parameters.target >>
    steps:
      - checkout
      - run:
          name: build tool
          command: mvn -B -V -DskipTests=true -Dmaven.javadoc.skip=true install
      - run:
          name: install << matrix.target >> pre-requisites
          command: |
            f=".circleci/scripts/install-linux-$TARGET.sh"; ! [ -x "$f" ] || "$f"
      - run:
          name: test $TARGET runtime
          command: |
            .circleci/scripts/run-tests-linux-$TARGET.sh
  test_runtime_target_group:
    machine: true
    parameters:
      target:
        description: The target
        type: string
        default: java
      group:
        description: The section
        type: string
        default: MAIN
    steps:
      - run: echo "Hello <<parameters.target>> <<parameters.group>>"

workflows:
  build:
    jobs:
      - test_java_tool_and_runtime
      - test_runtime_target: # invokes the parameterized job
          matrix:
            parameters:
              target: [ dart, go, python2, python3, javascript ]
      - test_runtime_target_group: # invokes the parameterized job
          matrix:
            parameters:
              target: [ cpp, dotnet, swift ]
              group: [ LEXER, PARSER, RECURSION ]